name: Quality Analysis

on:
  pull_request:
    branches: [main]
  push:

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test:cov
